- volk.c
On Linux cross-compile, case-sensitivity strikes.
> Fix MinGW compilation.

- volk.c
Uses dylib suffix if compiled on Apple.
For this to work, MoltenVK must be searchable on DYLD_LIBRARY_PATH.
> Add Apple support via MoltenVK

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- README.md
This PR removes AppVeyor build and adds Travis CI windows build instead. To make things simpler we also add a CMakeLists.txt that can be used to build the library for testing.
> Switch Windows builds to Travis CI

- .travis.yml
We now can use language: cpp and don't need to hunt cmake down since
Travis CI fixed their configs.
> Refactor Travis CI build script

- CMakeLists.txt
> fix for `error: undefined reference to dlopen` on linux

- volk.c
- volk.h
This change makes sure that including volk.h doesn't pull in windows.h
with it - windows.h is a *very* heavy dependency, and it's not that
necessary since we only need a few symbols from it in the header.
As a result, including volk.h is now 200-100ms faster on a very fast CPU
with a hot FS cache depending on whether WIN32_LEAN_AND_MEAN is defined
or not.
Fixes #21.
> Remove dependencies on windows.h

- volk.c
If compiling w/ -Wstrict-prototypes the compiler complains about these decls.
Add "void" to clarify that these are func protos with no params.
> Clarify function prototypes

- volk.c
The SDK ships with libvulkan.1.1.x.dylib, libvulkan.1.dylib, and libvulkan.dylib.
> Correct MacOS library name

- generate.py
- volk.c
- volk.h
Vulkan specification says that while core device-level commands and
device-level commands provided by device extensions can be loaded by
GDPA, device-level commands provided by instance extensions can't be.
Since we must use GIPA for these, the question is, do they need to be in
VolkDeviceTable?
This change treats these commands as instance-level by removing them
from VolkDeviceTable and loading them during volkLoadInstance with GIPA.
The justification is that the use-case for VolkDeviceTable is having
different function pointers for different devices when explicit mGPU is
used, and due to spec restrictions these functions can never have
different (per-device) function pointers.
Fixes #8.
> Fix loading of device-level commands provided by instance extensions

- volk.c
- volk.h
Disable clang-formatting for volk source files.
This will simplify integration with other projects, such as ANGLE,
where clang-formatting may significantly change the code and make
comparisons more difficult.
> Add clang-format comments

- volk.c
- volk.h
Add static VkInstance and VkDevice vars to track the last
instance and device for which global entrypoints have been loaded.
When calling volkLoadInstance() or volkLoadDevice(), update
tracking instance and device vars.
Provide volkGetLoadedInstance() and volkGetLoadedDevice() functions
to query the instance/device respectively for which global function
pointers have most recently been loaded.
This is useful for ANGLE where we iterate testing over different
single VkDevice objects on the same physical box. We can re-call the
volkLoad* functions and only incur the updates when needed.
> Add query interface for loaded instance/device

- .gitignore
- volk.c
- volk.h
- Fix forced redundancy in `volkLoadInstance` -> `volkLoadDevice` path, resolves #7 
- Fix two warnings about missing `(void)` in function prototype
- Add gitignore
> Add volkLoadInstanceOnly

- volk.c
The correct dlopen behaviour is to load libraries by SONAME. The current
behaviour can cause different versions of libvulkan to be loaded at
runtime. And having multiple loaders in the same app can have undesired
side-effects.
We keep the libvulkan.so fallback for cases Android platforms where only
that name may be available.
> Give precedence to libvulkan.so.1 over libvulkan.so

- .github/workflows/build.yml
- volk.h
This extension can't be used on SDK <140 because of a new function
introduced retroactively.
Also adds CI setup to catch issues like this in the future.
Fixes #48.
> Fix a regression with NVX_image_view_handle

- volk.c
As advised in #51. Opted for the define check since it works best for me.
> Add VOLK_DEFAULT_VISIBILITY define

- README.md
Hello there,
this simple PR adds instructions to call `volkLoadInstanceOnly(VkInstance instance)` when the user wants to load device-specific function pointers.
Cheers!
> Improve instructions for loading device-based function pointers

- CMakeLists.txt
Good day,
For case when added as header only, using cmake_using_subdir_headers
We can now use both : volk::volk_headers and volk_headers
target_link_libraries( foo PRIVATE volk::volk_headers)
Best regards
> Add namespace alias for libraries

- CMakeLists.txt
- volk.c
- volk.h
New entrypoints:
- vkGetPhysicalDeviceFragmentShadingRatesKHR
- vkCmdSetFragmentShadingRateKHR
Based on
- 1.2.157: https://github.com/KhronosGroup/Vulkan-Headers/commit/04306fa5d673a69db5a79af80011c688b64d7711
- 1.2.158: https://github.com/KhronosGroup/Vulkan-Headers/commit/320af06cbdd29848e1d7100d9b8e4e517db1dfd5
> Update to 1.2.158

- README.md
Fixed a typo on Building section of the README.md file: whereever -> wherever
> Fixed a typo on README

- CMakeLists.txt
- volk.c
- volk.h
New extension:
- `VK_NV_external_memory_rdma`
`vkGetSubpassShadingMaxWorkgroupSizeHUAWEI` was renamed to `vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI`
> Update to 1.2.184

- .github/workflows/update.yml
As you can see by looking at the [amount of actions](https://github.com/zeux/volk/actions) being run, it's entirely wasteful for the runner to run every day. Instead, only run the Thursdays in the evening (the latest spec update I found was 3pm). Also delivers most spec updates faster as we don't have to wait until Friday 9am for updates to be pushed. Should a spec update occur later, a manual trigger can still be done.
The 1.3.216 changelog reads:
> Change log for June 2, 2022 Vulkan 1.3.216 spec update:
>
> * Update release number to 216 for this update.
> * Note: most spec updates will occur on Thursdays going forward, not
Tuesdays.
> Fix: Only run action on thursdays

- CMakeLists.txt
The Vulkan SDK build process needs to be able to pass a CMake variable in to the Volk build indicating where the Vulkan-Headers install build resides.  Otherwise, Volk could end up building with an older version of the SDK that happens to be installed on the build system (as our CI systems have various different SDK/loader combinations installed, for test purposes).
This change causes Volk to respect a VULKAN_HEADERS_INSTALL_DIR CMake variable, if defined.  The variable must be checked before the presence of a Vulkan SDK is checked, to ensure that a random SDK installed on the system doesn't interfere with the build.
> sdk: support the Vulkan SDK build process

- .github/workflows/update.yml
Due to limitations of GHA, we have an option of:
- Not using scoped tokens, which breaks the actions dispatched on PRs and thus results in a risk of breaking the build
- Using scoped tokens, which fixes that, but breaks notifications if the token is created on behalf of the repository maintainer. It also requires recreating the token every year
For now let's go back to a token-less approach and add a manual build step to somewhat mitigate the breakage risk.
> Add 'build' step to update action

- volk.c
minwindef.h defines FARPROC without (void) argument list, so if it is already included when volk.c is compiled via VOLK_IMPLEMENTATION, gcc will emit an error (MSVC handles this mismatch fine).
Unfortunately, simply removing (void) results in a warning with Wstrict-prototypes even when volk.c is compiled as standalone. We could disable the warning with a pragma but for now we could simply reuse FARPROC definition from minwindef.h if it's already included.
Fixes #140
> Fix conflict between FARPROC definition and minwindef.h

- volk.c
- volk.h
This is normally not necessary to call if the instance survives until the application shutdown, but it might be useful in some cases where a clean and complete instance recreation is needed, or if the application wants to tear down the Vulkan instance and then create an OpenGL instance while making sure the Vulkan DLLs are unloaded.
Fixes #152.
> Implement volkFinalize function

- volk.c
dlopen on macOS is supposed to automatically search /usr/local/lib per dlopen man page. This behavior is customizable via DYLD_LIBRARY_PATH and DYLD_FALLBACK_LIBRARY_PATH, but even if neither is explicitly set /usr/local/lib should be a search path. Unfortunately, this does not happen anymore on modern macOS systems, and this is precisely where Vulkan SDK installs dylib by default.
This used to "work" in CMake builds that accidentally linked in libvulkan.dylib statically, because the library was already loaded into the process, but fixing that exposed this issue.
So we need to manually fallback to /usr/local/lib path. See https://developer.apple.com/forums/thread/737920 - looks like this change is intentional, and manual pages are out of date.
Fixes #163.
> Fall back to /usr/local/lib/libvulkan.dylib on macOS

- CMakeLists.txt
*BSD systems do not use libdl.
> CMake: Fix linking on *BSD systems

- volk.c
This adds framework binaries to the search list for the Vulkan Loader or MoltenVK on Apple platforms. The next version of the Vulkan SDK will be shipping both of these as Frameworks only on iOS, as the iOS app store strictly enforces the "no naked .dylib" rule.
> apple: Add support for loader or moltenvk in a framework

- CMakeLists.txt
The `VOLK_STATIC_DEFINES` and `VULKAN_HEADERS_INSTALL_DIR` cache variables in `CMakeLists` don't seem to do anything if you generate the cache without setting them because they will be booleans. As far as I understand it, `option` is for booleans and has always been. This fix swaps these variables to other types.
> CMake: cache variables that shouldn't be booleans are option

- volk.c
This change allows gcc to clean compile with Wall, pedantic and -Werror. Meson in particular toggles -pedantic in warning_level=3 which causes GCC compilation to fail.
The error, while technically not incorrect, it has been discussed since 2017 and it is unlikely to be fixed/changed on GCC's side [https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83584](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83584)
> Ignore pedantic check on function pointer cast for GCC

- CMakeLists.txt
There is no need to discovery the vulkan path with FindVulkan.cmake unless VULKAN_HEADERS_INSTALL_DIR was not set explicitly.
> CMake: Improve the include path discovery

- volk.h
When building volk with VK_USE_PLATFORM_XLIB_KHR, volk includes Xlib.h as a byproduct of including vulkan.h.
Xlib.h is not a very nice header: it defines a lot of unprefixed macros that may interfere with other code included after volk.h (e.g. it defines Convex which breaks Jolt Physics headers).
On Windows, we've been using a change that includes vulkan_win32.h manually after redefining the subset of windows.h that it needs. This change attempts to do the same for Xlib.h.
Unfortunately, this requires duplicating pretty much the entire vulkan.h to replace these bits; for Windows, there's only one expected platform that can be active at a given time, but on Linux applications might want up to 4 in rare cases (Xlib, Xlib Randr, Xcb, Directfb). The alternative would be to #undef the relevant …
> Remove dependency on Xlib.h

- volk.c
Fixes indentations which causes issues if compiling with clang where `misleading-indentation` is an error
> chore: fix indentations

- generate.py
- volk.c
- volk.h
To avoid issues with ABI compatibility of volk built with different sets
of defines, we now generate padding fields for each extension block with
the same number of function pointers. This should make sure that the
offset of every pointer for any given volk version remains stable,
simplifying binary builds.
Fixes #230
> Generate padding fields in VolkDeviceTable to preserve ABI
